version: "3.9"
services:
  backend:
    build: ./backend
    container_name: taskprinter-backend
    env_file: .env
    environment:
      - TZ=${TZ}
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: taskprinter-frontend
    env_file: .env
    environment:
      - VITE_API_BASE=${API_BASE}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: